### ISSUE TITLE
 Contribute.MD

### ISSUE THREAD

**Issue by Adesoji1** [iryna-kondr/scikit-llm#1]
We should have a contribute.Md file for users who want to contribute. I would also like to contribute to this project

**Comment by iryna-kondr** [comment]
Hi! Thank you for your interest. We will add `CONTRIBUTING.md` file in the nearest future.

**Comment by tarun-infiniteloop** [comment]
How to contribute, To this project? I mean, Is there any discord or something where some group of people is working on it, to make it big?

**Comment by OKUA1** [comment]
@tarun-infiniteloop not at the moment, but more details will follow soon.

**Comment by iryna-kondr** [comment]
@Adesoji1 @tarun-infiniteloop 

We have added a general `CONTRIBUTING.md` file. If you have a specific idea/suggestions, you could start a new discussion here: https://github.com/iryna-kondr/scikit-llm/discussions
