### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by ghaith-khlifi** [iryna-kondr/scikit-llm#10]
How to evaluate the zero shot classifier for multilabel task, can you make it adaptable to sikitlearn classification report

**Comment by OKUA1** [comment]
If you want to use the classification report from sklearn, it should be possible if you convert the labels into one-hot representation. 

A very simple way to do it with plain python:

`y = [['cat1', 'cat2'], ['cat2', 'cat3'], ['cat2']]
yh = [['cat1', 'cat2'], ['cat1', 'cat3'], ['cat1']]


# create a list of unique categories
categories = list(set(x for sublist in y for x in sublist))

# create a dictionary where the keys are the categories and the values are the indices
cat_to_index = {cat: index for index, cat in enumerate(categories)}

# transform the labels
y_transformed = [[1 if categories[i] in sublist else 0 for i in range(len(categories))] for sublist in y]
yh_transformed = [[1 if categories[i] in sublist else 0 for i in range(len(categories))] for sublist in yh]
`
