### ISSUE TITLE
Generating Natural Language

### ISSUE THREAD

**Issue by DeedahwarMazhar** [iryna-kondr/scikit-llm#15]
Hi,

First of all, great work and highly commendable.

Is there any way to generate a natural language response like gpt-3.5?

**Comment by OKUA1** [comment]
Hi! Currently, it is not possible to generate a natural language response. Could you tell more details about your use case and maybe we will be able to add it in the future.

**Comment by aiwalter** [comment]
just being able to call ChatGPT with scikit-learn `predict()` would be working?
