### ISSUE TITLE
Unable to use gpt4all

### ISSUE THREAD

**Issue by AnchitGupta22** [iryna-kondr/scikit-llm#32]
I followed all the steps as mentioned in the readme but I couldn't use gpt4all in my colab notebook. It keeps prompting me to install it (error: gpt4all is not installed, try 'pip install sckit-llm[gpt4all]') even though I added the installation code before running my code snippet. 

It's happening just with gpt4all as gpt 3.5 turbo atleast loads and works.

**Comment by OKUA1** [comment]
Could you share your code snippet and the exact error message/trace ?

**Comment by AnchitGupta22** [comment]
`# importing SKLLMConfig to configure OpenAI API (key and Name)
from skllm.config import SKLLMConfig

# Set your OpenAI API key
SKLLMConfig.set_openai_key("my-api-key")

# Set your OpenAI organization
SKLLMConfig.set_openai_org("my-org")

from skllm import ZeroShotGPTClassifier

# defining the model
clf = ZeroShotGPTClassifier(openai_model="gpt4all::ggml-gpt4all-j-v1.3-groovy")
clf = clf.fit(X_train, y_train)

from sklearn.metrics import classification_report

for split_name, dataset in zip(['train', 'validation'], datasets):
    X_i, y_i = dataset
    y_pred = clf.predict(X_i)
    print(f'\nSplit: {split_name}')
    print(classification_report(y_i, y_pred))
`

`ImportError: gpt4all is not installed, try `pip install scikit-llm[gpt4all]`
`

**Comment by OKUA1** [comment]
Did you try to restart the runtime after installing the package ? Otherwise, it might be reusing `gpt4all = None` as it was set during the failed import attempt.

**Comment by AnchitGupta22** [comment]
I tried that too. Still got the error.

**Comment by OKUA1** [comment]
We could not reproduce this issue in colab. Maybe you could try to create a fresh instance and check whether the problem is still present.
