### ISSUE TITLE
Wrong output in GPTTranslator

### ISSUE THREAD

**Issue by jorgeston** [iryna-kondr/scikit-llm#34]
Hi, 

I have used GPTTranslator in some list of mixed english and spanish text, and the output that I get looks at follows (truncated). 

I tried two times and the output ramains the same:

> '\```Requisitos para entidades culturales.\``` \n\```Requirements for cultural entities.\``` \n\```Requisitos para entidades culturales.\```',
>  'Requisito de identificación de alcohol.',
>  'Ampliar plazo matrimonio. \n\nTranslation: Ampliar el plazo de matrimonio.',
>  'Bono de invierno incrementado.',
>  'Mejora del seguro de GPS.',
>  'Retiro de fondos.',
>  'Reingreso ilegal penalizado.',
>  'Modificación de protección del agua.',
>  'Autorización para portar armas.',
>  'Adición de reembolso de aerolínea.',
>  'Licencia adulterada.',
>  'Renombrar el aeropuerto en honor a Margot Duhalde.',
>  'Alquiler regulado.',
>  'Modificaciones laborales.',
>  'Ley de igualdad de edad.',
>  'Reforma constitucional.',
>  'Arborización por nacimiento.',
>  'Sanciones de armas más duras.',
>  '\```Comités de seguridad.\``` \n(Translated to Spanish: Comités de seguridad.)',
>  'Modificaciones legales para migrantes.',
>  'Criminalizando la negación de los derechos humanos.',
>  'Reforma de empresas estatales.',
>  'Exención de multa.',
>  'Prioridad de educación sexual de los padres.',
>  'Secretos bancarios ampliados.',
>  'Modificación de la ley del VIH.',
>  'Cambios en la ley de votación.',
>  '\```Subsistema de Inteligencia.\``` \n(Spanish)'

The input (truncated) is:

> ['Requisitos para entidades culturales.',
>  'Alcohol ID requirement.',
>  'Ampliar plazo matrimonio.',
>  'Bono Invierno incrementado.',
>  'GPS insurance improvement.',
>  'Retiro de fondos.',
>  'Illegal re-entry penalized.',
>  'Water protection modification.',
>  'Porte de armas autorizado.',
>  'Airline refund addition.',
>  'Licencia adulterada.',
>  'Rename airport after Margot Duhalde.',
>  'Arriendo regulado.',
>  'Modificaciones laborales.',
>  'Age equality law.',
>  'Constitutional reform.',
>  'Arborización por nacimiento.',
>  'Tougher weapon penalties.',
>  'Comités de seguridad.',
>  'Legal modifications for migrants.',
>  'Criminalizing human rights denial.',
>  'State-owned companies reform.',
>  'Exención de multa.',
>  "Parents' sexual education priority.",
>  'Secretos bancarios ampliados.',
>  'HIV law modification.',
>  'Voting law changes.',
>  'Subsistema de Inteligencia.']

**Comment by OKUA1** [comment]
Hi. Just to clarify that I got it right: you are translating from mixed Spanish/English into Spanish, right? I think whenever the text is already in Spanish, the model might be confused what to do. We will try to investigate this issue and improve the prompt in the next releases. Also, for multilingual tasks we always encourage to use gpt4 as it usually has a substantially better performance.

**Comment by jorgeston** [comment]
Yes, you're right. 

Sadly, i can't use gpt4 yet (I will suscribe to waitlist)

**Comment by OKUA1** [comment]
We reworked the prompt of the translator. It should have a more stable behavior now when encountering an input in the target language. The updated prompt will be available in the next release (probably within 1-2 weeks). Meanwhile it is possible to install the latest version directly from github if you would like to try it out: `pip install git+https://github.com/iryna-kondr/scikit-llm`

**Comment by OKUA1** [comment]
This issue should be resolved in the v0.3.0
