### ISSUE TITLE
is there a way to turn off the tqdm progress bar ?

### ISSUE THREAD

**Issue by mfahadakbar** [iryna-kondr/scikit-llm#37]
Hi, 

I wonder if there is a way to suppress the tqdm progress bar during fitting.

Thank you

**Comment by OKUA1** [comment]
Hi, 
Currently scikit-llm estimators do not have a verbosity parameter. So the only way to disable tqdm is by modifying its init method (this would affect it globally though).

```python
from tqdm import tqdm
from functools import partialmethod

tqdm.__init__ = partialmethod(tqdm.__init__, disable=True)
```

**Comment by mfahadakbar** [comment]
thank you
