### ISSUE TITLE
Text Vectorization and Dynamic Few-Shot Text Classification not working

### ISSUE THREAD

**Issue by Slim0120** [iryna-kondr/scikit-llm#42]
Hello,

I have the following code in my jupyter notebook:

!pip install scikit-llm
from skllm.config import SKLLMConfig
SKLLMConfig.set_openai_key("<my azure openai key>")
SKLLMConfig.set_azure_api_base("<my azure api base")

from skllm.datasets import get_multilabel_classification_dataset
X, y = get_classification_dataset()

from skllm import DynamicFewShotGPTClassifier
GPT_model3 = DynamicFewShotGPTClassifier(n_examples=3)
GPT_model3.fit(X, y)
GPT_labels3 = GPT_model3.predict(X)

from skllm.preprocessing import GPTVectorizer
model = GPTVectorizer()  
vectors = model.fit_transform(X)

Both dynamic few shot classifier and GPTvectorizer are giving me the following issues:

RuntimeError                              Traceback (most recent call last)
Cell In[135], line 4
      2 X, _ = get_classification_dataset()
      3 model = GPTVectorizer()  
----> 4 vectors = model.fit_transform(X)

File ~/anaconda3/lib/python3.10/site-packages/sklearn/utils/_set_output.py:142, in _wrap_method_output.<locals>.wrapped(self, X, *args, **kwargs)
    140 @wraps(f)
    141 def wrapped(self, X, *args, **kwargs):
--> 142     data_to_wrap = f(self, X, *args, **kwargs)
    143     if isinstance(data_to_wrap, tuple):
    144         # only wrap the first output for cross decomposition
    145         return (
    146             _wrap_data_with_container(method, data_to_wrap[0], X, self),
    147             *data_to_wrap[1:],
    148         )

File ~/anaconda3/lib/python3.10/site-packages/skllm/preprocessing/gpt_vectorizer.py:94, in GPTVectorizer.fit_transform(self, X, y, **fit_params)
     79 def fit_transform(self, X: Optional[Union[np.ndarray, pd.Series, List[str]]], y=None, **fit_params) -> ndarray:
     80     """
     81     Fits and transforms a list of strings into a list of GPT embeddings.
     82     This is modelled to function as the sklearn fit_transform method
   (...)
     92     embeddings : np.ndarray
     93     """
---> 94     return self.fit(X, y).transform(X)

File ~/anaconda3/lib/python3.10/site-packages/sklearn/utils/_set_output.py:142, in _wrap_method_output.<locals>.wrapped(self, X, *args, **kwargs)
    140 @wraps(f)
    141 def wrapped(self, X, *args, **kwargs):
--> 142     data_to_wrap = f(self, X, *args, **kwargs)
    143     if isinstance(data_to_wrap, tuple):
    144         # only wrap the first output for cross decomposition
    145         return (
    146             _wrap_data_with_container(method, data_to_wrap[0], X, self),
    147             *data_to_wrap[1:],
    148         )

File ~/anaconda3/lib/python3.10/site-packages/skllm/preprocessing/gpt_vectorizer.py:74, in GPTVectorizer.transform(self, X)
     71 embeddings = []
     72 for i in tqdm(range(len(X))):
     73     embeddings.append(
---> 74         _get_embedding(X[i], self._get_openai_key(), self._get_openai_org())
     75     )
     76 embeddings = np.asarray(embeddings)
     77 return embeddings

File ~/anaconda3/lib/python3.10/site-packages/skllm/openai/embeddings.py:48, in get_embedding(text, key, org, model, max_retries)
     46         error_type =  type(e).__name__
     47         sleep(3)
---> 48 raise RuntimeError(
     49     f"Could not obtain the embedding after {max_retries} retries: `{error_type} :: {error_msg}`"
     50 )

RuntimeError: Could not obtain the embedding after 3 retries: `InvalidRequestError :: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>`. '

If you could help me figure out this issue, that would be great!

**Comment by OKUA1** [comment]
@Slim0120 as stated in the docs, neither of the skllm estimators you are trying to use currently support the Azure backend. We are planning to extend this in the next versions.

**Comment by Slim0120** [comment]
Okay great, it is working well with the regular OpenAI API now. Another followup question. I have a fully labeled dataset with X = text from PSAs and y = one of three labels about the main theme of the message. N=200. I wanted to examine how well GPT performs vs. other scikitlearn classifiers, so I sent up my code like this: 

X = dataset_df["arg_text"]
y = dataset_df["recoded_theme"]

!pip install scikit-llm
from skllm.config import SKLLMConfig
SKLLMConfig.set_openai_key("<my api>")
SKLLMConfig.set_azure_api_base("<my azure api base>")

from skllm import FewShotGPTClassifier
GPT_model2 = FewShotGPTClassifier(openai_model="azure::CloudFellowship")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

GPT_accuracy_scores2 = cross_val_score(GPT_model2, X, y, cv=cv, scoring='accuracy')
GPT_precision_scores2 = cross_val_score(GPT_model2, X, y, cv=cv, scoring='precision_macro')
GPT_recall_scores2 = cross_val_score(GPT_model2, X, y, cv=cv, scoring='recall_macro')
GPT_f1_scores2 = cross_val_score(GPT_model2, X, y, cv=cv, scoring='f1_macro')

From this code, how many "few shot" learning examples are being used? And what would be the difference if I kept the same code but used ZeroShotGPTClassifier instead?

Thanks for your help!

**Comment by OKUA1** [comment]
@Slim0120 When you use the regular `FewShot`, all of the examples from the training set are going to be used (hence you should probably use larger test set / more folds). In contrast, `DynamicFewShot` allows to manually specify the number of instances to be used, which is a more suitable option for larger training sets.

If you change it to `ZeroShot` it will still work, but the "training" set won't be used for anything. Therefore, there is no reason to use cross validation in this scenario.

**Comment by Slim0120** [comment]
Got it, thank you very much!
