### ISSUE TITLE
'GPT4All' object has no attribute 'chat_completion'

### ISSUE THREAD

**Issue by hover6677** [iryna-kondr/scikit-llm#47]
if GPT4All is None:
        raise ImportError(
            "gpt4all is not installed, try `pip install scikit-llm[gpt4all]`"
        )
    if model not in _loaded_models.keys():
        _loaded_models[model] = GPT4All(model)

    return _loaded_models[model].chat_completion(
        messages, verbose=False, streaming=False, temp=1e-10
    )

**Comment by OKUA1** [comment]
scikit-llm version uploaded to pypi is not compatible with gpt4all>=1.0.0. You can either install the latest scikit-llm directly from GitHub master branch, or downgrade gpt4all.
