### ISSUE TITLE
Dependency VertexAI breaks Python installation

### ISSUE THREAD

**Issue by Zahlii** [iryna-kondr/scikit-llm#48]
First of all, it seems that vertexai is not supposed to be used and merely a placeholder for google-cloud-aiplatform.
Secondly, the current wheel (at least on MacOS for me) is broken, as it contains a __init__.py file with the following content:

```
# ...

raise ImportError(
    "To use the Vertex AI SDK, install the google-cloud-aiplatform package."
)
```

However, this is not placed into site-packages/vertexai/__init__.py, BUT INSTEAD AT THE ROOT OF SITE-PACKAGES. This means every other module can NOT be imported anymore. I think this is an issue with the original wheel file, however since it is not needed I'd appreciate an updated version with the dependency removed.

<img width="243" alt="image" src="https://github.com/iryna-kondr/scikit-llm/assets/218582/573fdd5f-e9c6-4433-a1aa-4d20c73f806d">

**Comment by OKUA1** [comment]
@Zahlii yes, you are right. Vertexai dependency should not be required and will be removed.
