### ISSUE TITLE
Supporting NER tasks

### ISSUE THREAD

**Issue by MateusCichelero** [iryna-kondr/scikit-llm#62]
Could we add support for named entity recognition tasks to the library? I see that the user interface would not change much from what was applied in the multi-label classification method, with the difference that instead of the entire text input being classified as one or multiple labels, we would have distinct entities from the text being recognized and labeled (the user could also give a semantic list of possible entities to be recognized as input).

**Comment by OKUA1** [comment]
Hello @MateusCichelero , 

Thanks for your suggestion. We will evaluate the possibilities of adding NER in the future.

**Comment by daniau23** [comment]
Will that of Topic modelling be added too?

**Comment by OKUA1** [comment]
@daniau23 maybe, but hard to say at the moment

**Comment by fvillena** [comment]
You could use https://github.com/plncmm/llmner

**Comment by iryna-kondr** [comment]
Resolved by #103
