### ISSUE TITLE
Update Readme for Azure users

### ISSUE THREAD

**Issue by mcazim98** [iryna-kondr/scikit-llm#65]
I was facing some issues configuring the Api keys and the Api base for my deployed resource on Azure. I was able to solve it using the azure documentation, i think adding these changes would help someone trying to configure it faster.

*Below is the proposed change to the ReadMe.*

### Using Azure OpenAI

```python
from skllm.config import SKLLMConfig

SKLLMConfig.set_openai_key("<YOUR_KEY>")  # use azure key instead
SKLLMConfig.set_azure_api_base("<API_BASE>") # your endpoint should look like the following https://YOUR_RESOURCE_NAME.openai.azure.com/

# start with "azure::" prefix when setting the model name
model_name = "azure::<model_name>"
# e.g. ZeroShotGPTClassifier(openai_model="azure::gpt-3.5-turbo")
```

Note:
1. Azure OpenAI is not supported by the preprocessors at the moment.
2. The the openai_model should be the deployment name for the resource.
3. To find the API_KEY and the Azure Api Base : [Azure OpenAi Documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line&pivots=programming-language-python)

**Comment by OKUA1** [comment]
Good point. We are in the process of completely reworking the documentation and will include the suggested changes.

**Comment by PRASADA1207** [comment]
Connectivity to Azure Open AI gpt-35-turbo model
If I have to use Azure Open AI how can I do, even thoughI did as mentioned above .I am getting the below error

ZeroShotGPTClassifier(openai_model="azure::gpt-3.5-turbo")

I am getting error

Could not obtain the completion after 3 retries: `InvalidRequestError :: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.`
None
Could not extract the label from the completion: 'NoneType' object is not subscriptable.
@OKUA1 @mcazim98  Can you please help ?
![1](https://github.com/iryna-kondr/scikit-llm/assets/76814154/0a828d12-5b78-41c9-9432-6d6d5e9f1f18)

**Comment by mcazim98** [comment]
The openai model that you deployed should have a deployment name. if you have a model deployed, go to https://oai.azure.com/ and to the **Deployments** tab, there you should find your deployment name. 
```clf = ZeroShotGPTClassifier(openai_model="azure::<deployment_name>").```
If you still get the error, try checking if you set the SKLLMConfig.set_azure_api_base(https://YOUR_RESOURCE_NAME.openai.azure.com/) correctly.
@PRASADA1207
