### ISSUE TITLE
Integration of other LLMs

### ISSUE THREAD

**Issue by ajayarunachalam** [iryna-kondr/scikit-llm#69]
Anything in pipeline to integrate other Large Language Models such as LLAMA, GPT-J, GPT4ALL -J, AUTO-GPT and others?  
Quick Reference: https://github.com/ajayarunachalam/pychatgpt_gui

**Comment by OKUA1** [comment]
GPT4ALL is already integrated. Overall integrating local LLMs is not too high on the priority list as according to our observations their performance on the skllm related tasks is not good enough.

**Comment by ajayarunachalam** [comment]
Okay, thx for responding.
