### ISSUE TITLE
prompt-engineering ? 

### ISSUE THREAD

**Issue by jalotra** [iryna-kondr/scikit-llm#7]
hey fellas, according to this : [link](https://github.com/openai/openai-cookbook/blob/main/techniques_to_improve_reliability.md)
prompting to classify can be made better, by using techniques like Chain of Thought and Few Shot training. 

Want this incorporated ?

**Comment by OKUA1** [comment]
Hi @jalotra,

Few shot prompting is planned as a separate class (see roadmap). 

The prompt itself could possibly be improved, so we are open to suggestions. Changing the prompt would require thorough testing to make sure it is at least as good as the current one.

Eventually, we are also planning to support user-defined prompt templates, as they could be better tailored for specific tasks.

**Comment by casezhao** [comment]
it seems like a prompt project
