### ISSUE TITLE
Azure OpenAI Embeddings

### ISSUE THREAD

**Issue by Ioannis-Pikoulis** [iryna-kondr/scikit-llm#76]
You have added support for Azure OpenAI GPT models. Please add support for Azure OpenAI embedding models too. Due to this problem, I can't use the GPTVectorizer as well as Dynamic Few Shot Classification.

**Comment by OKUA1** [comment]
@Ioannis-Pikoulis this will be added in either v1.0 or v1.1. No specific estimates, but we are planning to release both versions this year.

**Comment by iryna-kondr** [comment]
Resolved with https://github.com/iryna-kondr/scikit-llm/pull/94
