### ISSUE TITLE
Predictions scores for the ZeroShotGPTClassifier

### ISSUE THREAD

**Issue by Puturbold** [iryna-kondr/scikit-llm#77]
I am trying to use the ZeroShotGPTClassifier and evaluate the results based on the prediction score. Is there a way to get the prediction score?

The HuggingFace ZeroShotClassifier returns a dictionary with labels and scores as lists. I am looking for a way to score the labels. Otherwise, there is no way to evaluate the labels from the ZeroShotClassifier. Especially if it returns a random label when no label matches.

**Comment by OKUA1** [comment]
Probably manual evaluation would still be the best bet if no labeled data is available. Also having prediction scores would not necessarily help, as the model can be incorrect in a very confident way (a high score for a wrong label).
