### ISSUE TITLE
Consider updating package requirements

### ISSUE THREAD

**Issue by Ananya-Joshi** [iryna-kondr/scikit-llm#83]
<img width="1492" alt="Screenshot 2024-02-03 at 11 10 07 PM" src="https://github.com/iryna-kondr/scikit-llm/assets/11541884/d3c9209e-a7d4-4b10-b561-32b8ae7f781d">

Consider remaining compatible with the openai package. 

Specs: MacBook Pro 2019

**Comment by OKUA1** [comment]
Hi. You are using an outdated version of scikit-llm. Please upgrade to v1.
