### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by lpfgarcia** [iryna-kondr/scikit-llm#90]
ZeroShotGPTClassifier.predict must return an np.array instead of a list.

**Comment by lpfgarcia** [comment]
https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html

**Comment by OKUA1** [comment]
Hi @lpfgarcia, 

I agree, It would be better that all of the predictions are numpy arrays. There was a historical reason what it is not, but since v1.0 it should not be applicable anymore. 

If you are willing to contribute, you can create a PR with the proposed change.
